#!/bin/bash

. vars

docker run -itv $HOME:/home/spacemacs/home \
  -v $HOME/dotfiles:/home/spacemacs/dotfiles \
  -v $HOME/.gitconfig:/home/spacemacs/.gitconfig \
  -v $HOME/.ssh:/home/spacemacs/.ssh \
  -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent \
  ${IMAGE}