#!/bin/bash

REGISTRY=quay.io/
IMAGE_PREFIX=jgmize
IMAGE_NAME=spacemacs-tmux
VERSION=${VERSION:-$(git rev-parse --abrev-ref HEAD)}
IMAGE=${REGISTRY}${IMAGE_PREFIX}/${IMAGE_NAME}:${VERSION}

docker run -itv $HOME:/home/spacemacs/home \
  -v $HOME/dotfiles:/home/spacemacs/dotfiles \
  -v $HOME/.gitconfig:/home/spacemacs/.gitconfig \
  -v $HOME/.ssh:/home/spacemacs/.ssh \
  -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent \
  ${IMAGE}